#!/bin/bash

echo "Enter 1 to start hadoop processes"
echo "Enter 2 to stop hadoop processes"
echo "Enter 3 to start hbase process"
echo "Enter 4 to stop hbase process"
echo "Enter 5 to start thrift process (needed for HappyBase)"
echo "Enter 6 to start hbase shell"


echo "Enter 7 to exit"

read opt

if [[ $opt -eq 1 ]]; then
  echo "Hadoop is now starting. Be patience!"
  start-dfs.sh
  start-yarn.sh
  echo "All hdfs process are mentioned below"
  jps
fi

if [[ $opt -eq 2 ]]; then
  echo "Hadoop is now stopping. Be patience!"
  stop-dfs.sh
  stop-yarn.sh
  jps
fi

if [[ $opt -eq 3 ]]; then
  echo "Hbase is now starting. Be patience!"
  /usr/local/hbase/bin/start-hbase.sh
  echo "Hbase process (hmaster) is mentioned below"
  jps
fi

if [[ $opt -eq 4 ]]; then
  echo "Hbase is now stopping. Be patience!"
  /usr/local/hbase/bin/stop-hbase.sh
  echo "Hbase process (hmaster) shouldn´t be mentioned below"
  jps
fi

if [[ $opt -eq 5 ]]; then
  echo "Thrift is now starting. Be patience!"
  /usr/local/hbase/bin/hbase thrift start
fi

if [[ $opt -eq 6 ]]; then
  echo "Hbase shell is now starting. Be patience!"
  /usr/local/hbase/bin/hbase shell
fi
if [[ $opt -eq 7 ]]; then
  echo "Thank you!"
fi
